### ISSUE TITLE
EMERGENCY - HUGE BLARING INSULTING ISSUES.

### ISSUE THREAD

**Issue by dYale** [joshuakopman/PandemicPictures#2]
Hi there, my name is not relevant to the extreme urgency of what I come here today to discuss. It is a matter of grave importance that cannot wait for any sort of preamble or introductions. If we had time for such nonsense than I would most assuredly say something endearing and self affirming but the unfortunate truth is the magnitude of me getting straight to the point outstrips the societal and sociological benefits of human interactions and providing extra context. Why are you still reading this, it is not important you has MASSIVE BLARING OUTSULTING security sadness. Look, I want you to succeed, I want you to thrive but that's not going to happen unless you focus. Without further ado let me introduce to you, my squeeze of the lemon mountaintop man! 

**I see a huge security vulnerability right now on all the lines of code including and especially the HTML, CSS, and Silverlight integrations.** PLESAE ADD EMOJI BECAUSE IT WILL SAVE LIVES

**Comment by dYale** [comment]
_**### HELLO IS ANYONE THERE?**_

**Comment by dYale** [comment]
HI THERE! In my perusings of my recently activity of actively saving the internet, I noticed the  @aliciahurst has assigned this issue to @joshuakopman. And I have one **extremely urgent** followup question:

**Does it?**

The answer can be help greatly. please advice

**Comment by joshuakopman** [comment]
Hi there, @dYale ! Thank you for your contribution to our humble repository and the open source community at large! Your requests are very importance to us and will be handled in the order in which they are received. 

Your current spot in our customer support queue is: **1**. 
Your estimated wait time is: **The heat death of the universe**.

Rest assured, our engineers are working tirelessly brainstorming ways to prolong addressing your concern while simultaneously handwaving it as a feature and not a bug, because I mean really who are _YOU_ to tell _OUR_ rockstar wizard principal code ninjas to investigate your _poor wittle issue_.

We'd respond further, but at this very moment we are blaming our product team for your grievance due to their murky acceptance criteria clearly written by a motley crew of luddites.

**Comment by dYale** [comment]
Thank for for reading between my lines. Your response is indicative of a well endowed bucket of gumption. I am quite concerned however that you are aware of my _wittle_ stature. If you are spying on me, you may continue but just know that there is a corner of my pitiful heart that questions the legitimacy of your Canadian citizenship.

Furthermore and hereunto, this is forsure a product problem, it's baffling that they did not think of the security, scalability, and infrastructure requirements, what are they even good for? 

Please defend your failures @aliciahurst

**Comment by aliciahurst** [comment]
Hi @dYale. Here at Pandemic Pictures, we take each and every inquiry seriously; please be advised that we apply equal gravity to ignoring dumb questions as well. Duly, we live by the company value "ownership, together, but through influence, not authority, because we cannot truly possess anything in this world," in which we have a fully dependent and mostly-trusting relationship with engineering. To that end, I uphold my counterpart's decision to close out this issue and will use the time saved responding to continue our AOL for Dummies book. Thank you most unkindly once again for submitting! 

sent from my iPhone
